services:

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      RABBITMQ_DEFAULT_USER: user_library_management
      RABBITMQ_DEFAULT_PASS: 12345678
    ports:
      - '5672:5672'
      - '15672:15672'

  library-management-database:
    image: 'postgres:16.3'
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: user_library_management
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5400:5432'

networks:
  library-management-network:
    name: library-management-network
    driver: bridge
