services:

  library-management-database:
    image: 'postgres:16.3'
    container_name: library-management-database
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: user_library_management
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5400:5432'

networks:
  library-management-network:
    name: library-management-network
    driver: bridge
